var VChatData = {
'e11' : 'Independent. Attract backstabbers. Do things in halfhearted manner.',
'e12' : 'Speaks bluntly. Attract backstabbers without any knowledge.',
'e13' : 'Fiery temper. Very impatient. Busy individual.',
'e14' : 'Good planner. Well organized. Lacks the finishing touch.',
'e15' : 'Believes in own principle strongly.',
'e16' : 'Works alone to achieve success and wealth. Modern and stylish outlook.',
'e17' : 'Attracts supporters that end up exerting pressure onto you. Overseas travel.',
'e18' : 'On the road often and having lots of pressure. Active mobility.',
'e19' : 'Involves with business or career that requires the individual to work alone.',
'e21' : 'Speaks with authority.',
'e22' : 'Soft heated. Talkative. A person that takes before giving. Selfish.',
'e23' : 'Emotional. Easily Agitated.',
'e24' : 'Excels in business presentation. Communicates well.',
'e25' : 'Speaks with a strong sense of principle. Able to attract attention.',
'e26' : 'Loves to center topics of dicussion around finance.',
'e27' : 'Charismatic individual that easily attracts supporters.',
'e28' : 'Always busy and very talkative. Likely to be in sales.',
'e29' : 'A person that loves to talk business.',
'e31' : 'A person that often needs an extra push before anything is done.',
'e32' : 'Fast talker. Person who speaks without worrying about consequences.',
'e33' : 'Extremely emotional. Very hyper. Aggressive and impatient.',
'e34' : 'Person with a quick mind. fast reaction.',
'e35' : 'Emotional. Unpredictable mood swing. easily provoked.',
'e36' : 'Big spender.',
'e37' : 'A person that turns supporters away.',
'e38' : 'Very emotional and under great stress. Always busy.',
'e39' : 'Busy seeking busuness opportunities but end up going round in circle.',
'e41' : 'Ideas being stolen regularly.',
'e42' : 'Good planner and presenter.',
'e43' : 'A fast planner that is able to attract lots of helping hands.',
'e44' : 'Lots of plans and ideas. Over organized. Will only execute if it benefits you.',
'e45' : 'Plan to succeed regardless of Consequences. Cunning individual.',
'e46' : 'Financial planner.',
'e47' : 'A good advisor and often plans for others.',
'e48' : 'A busy planner or organizer. Always under pressure but often ends up going round in circle.',
'e49' : 'Busuness strategist.',
'e51' : 'A man of principle. Very selfcentered. Travel often.',
'e52' : 'Stubborn in nature. Speaks with strong principle.',
'e53' : 'Emotional and impatient.',
'e54' : 'Plans to succeed regardless of consequences.',
'e55' : 'Very stubborn. Selfish. Short tempered. Emotional where can lead to selfdestruction.',
'e56' : 'Very careful with finance. Miser.',
'e57' : 'Have lots of opportunity to meet with high ranking government officials or high network individuals.',
'e58' : 'Create individual but often has to undertake work initiated by the individual.',
'e59' : 'Conservative in thinking.',
'e61' : 'Individual that loves to spend money on them.',
'e62' : 'A person that does not keep to his words. Often ends up where it begins.',
'e63' : 'Bug spender; keen on investment.',
'e64' : 'Investment spent on education and acquiring knowledge.',
'e65' : 'Miser.',
'e66' : 'Money is made through roller coaster manner-> ups and downs.',
'e67' : 'Loves to entertain friends.',
'e68' : 'A keen researcher. Difficult to conserve cash.',
'e69' : 'Loves investments. Risk taker.',
'e71' : 'Attracts backstabber.',
'e72' : 'Attracts supporters. friendly character.',
'e73' : 'Supporters come and go easily.',
'e74' : 'Mentors that would provide you word of wisdom and advice.',
'e75' : 'Friends or supporters would turn their backs on you vice versa.',
'e76' : 'Supporters providing you with capital for investment or assistance.',
'e77' : 'Lots of supporters but you tend to take advantage of them.',
'e78' : 'Supporters would give you a lots of pressure.',
'e79' : 'Supporters would help you achieve success; they might end up becoming your business partners.',
'e81' : 'A hardworking and worrisome individual. Busy running about.',
'e82' : 'Instructions given often falls into dear ear. End up resolving everything yourself.',
'e83' : 'Emotional and very impatient. Easily provoked.',
'e84' : 'Lots of ideas but ends up going round in circle.',
'e85' : 'Creative individual but often creates obstacles for you.',
'e86' : 'Have a lots of creative ideas to make money. Travels a great deal.',
'e87' : 'Hard work would be appreciated. Exerts pressure onto supporters.',
'e88' : 'Very busy. Lacks focus. Emotional and under lots of pressure.',
'e89' : 'Going round in circle with no breakthrough.',
'e91' : 'Lead a solitude life. Lonely.',
'e92' : 'Strong convincing power. Key discussion focus on business opportunities.',
'e93' : 'Goes round in circle but limited to a narrow field.',
'e94' : 'Academically in tuned but without clear goals in mind.',
'e95' : 'You are often the key obstacle to success. Often thinks about your own self instead of others. Selfish.',
'e96' : 'Business or investments would yield handsome return.',
'e97' : 'Charismatic individual. Able to attract lots of supporters.',
'e98' : 'Actions that yield no results. Ends up where it begins.',
'e99' : 'Lots of business opportunities. will result in lack of focus; too greedy.',
'e111' : 'ONE possesses leadership quality with an authoritative personality.  The leadership skills are being supported with the ',
'e112' : 'quality of initiation.  ONE initiates spontaneously given any circumstances and role delegations. ONE will not hesitate to take ',
'e113' : 'the front line if necessary, and not hesitate to take on responsibilities when projects face obstacles or failures.  People tend to ',
'e114' : 'show high respect to number ONE because of their leadership qualities.  ONE has a strong analytical mind. They are creative ',
'e115' : 'in mind mapping and executing task systematically.  They are often never short of alternatives when carrying projects or  ',
'e116' : 'in need to find solutions.  ONE is very independent and self-reliance, often appears to be in solitude.',
'e117' : '',
'e118' : '',
'e211' : 'TWO is vocal and communicative.  Do not hesitate to express their opinions and emotions. They possess skilful pleasantries ',
'e212' : 'and acquire the ability to cajole those around. Their collected calmness and openness makes them excel in social gatherings ',
'e213' : 'and versatile in interpersonal leverage.  TWO is with strength in charismatic skill, they shape themselves to be a mediator in ',
'e214' : 'public relations. Sometimes their chattiness may appear to be bad-mouthed and unintentionally creates misunderstandings. ',
'e215' : 'TWO are hardworking and sensitive with people around them.  They are normally matured in their thoughts. No doubt they ',
'e216' : 'may appear to listen earnestly to other people suggestions, at the end of the day they make their own decisions despite well ',
'e217' : 'intended advises.  They can be very determined individual.',
'e218' : '',
'e311' : 'THREE is moving forward and often plays active role in whatever they are assigned with.  They take action without hesitation ',
'e312' : 'and at times too aggressively. Do not tolerate tardiness and can be impatient getting things done. Their forcefulness within ',
'e313' : 'inspires them to take up many challenges in their environment.  THREE possesses many talents and skills.  They have the ',
'e314' : 'ability to map their thinking and analyse logically in a systematic approach.  Their optimism paves them to evaluate in clear ',
'e315' : 'and concise mind, and filter the right and the wrong.  THREE possesses talent and has the skills to differentiate logically and ',
'e316' : 'maturely. They fall short with their aggressiveness and impatience, which can easily spark off their temperament, but ',
'e317' : 'fortunately fizzle to a quick and short-lived temper.  THREE does not hesitate to express vocally and can be callous if left ',
'e318' : 'unchecked.',
'e411' : 'FOUR is knowledge seeking and a systematic planner and organiser.  Diligent in seeking knowledge and constantly striving ',
'e412' : 'to be informed makes FOUR academically acumen especially making decisions. The mind strives on a logical and analytical ',
'e413' : 'pattern, and a step-by-step practical pattern in mind-construction moulds FOUR to become sharp and acute planners.  You ',
'e414' : 'would not often find FOUR executing their moves or plans without having in-depth thoughts and often detailed research in ',
'e415' : 'every sense.  FOUR is straightforward, trustworthy and compassionate.  FOUR is outgoing and delights in going around. Their ',
'e416' : 'passion for knowledge ignites the thirst for travelling and combined with attributes, makes them wise and charismatic with ',
'e417' : 'people.  FOUR is a survival number that means they have the ability to confront obstacles and come out of it successfully.  ',
'e418' : 'FOUR is either particular about punctuality or totally lost in it.',
'e511' : 'FIVE is strong characters and firmly stand by their sense of principles.  They do not easily eradicate once they embrace their ',
'e512' : 'principles and beliefs.  They are usually in a position where they are above many.  They possess a stubborn streak and at times ',
'e513' : 'strongly willed. But they are realistic, grounded, firm and not easily cajoled once they have set their beliefs or rules that ',
'e514' : 'governed their personal characteristics.  This makes them natural leaders. Their acumen of leadership qualities makes it ',
'e515' : 'possible for them to take up challenges, handle pressure from peers and acquire success and recognition.  FIVE also possesses ',
'e516' : 'stubbornness, and can be quite emotional, unless he/she can learn to relax their shortcomings. FIVE is likely to encounter more ',
'e517' : 'obstacles than success.',
'e518' : '',
'e611' : 'SIX is a productive number with acumen in wealth and financial matters.  SIX is a practical and a realist.  SIX enjoys ',
'e612' : 'luxurious life style and associate themselves in popular places and people. With the combination of these qualities, SIX is ',
'e613' : 'regarded as well mannered, sociable and respectful. SIX can also be arrogant and proud in nature. They do not easily condoned ',
'e614' : 'to meager position and highly maintain their status quo. They are conservative in decision-making, often takes calculated risk. ',
'e615' : 'SIX makes a good executive, as they are responsible and often looks after the interest of their backers.',
'e616' : '',
'e617' : '',
'e618' : '',
'e711' : 'SEVEN is a sociable number and relates to people easily. They blend in with people effortless, well-liked and handle people ',
'e712' : 'with eloquence.  Their social skills in public relation accentuate many supporters.  SEVEN are intense with their emotions. ',
'e713' : 'They are strongly grateful to those who had once helped them. SEVEN is argumentative and opinionated with no limit to ',
'e714' : 'speech and will not hesitate to manipulate in a conversation even criticise openly.  They are fickle minded and inconsistent ',
'e715' : 'with their decisions.',
'e716' : '',
'e717' : '',
'e718' : '',
'e811' : 'EIGHT represents responsibility and mobility.  EIGHT is constantly on the move, busy searching for something or the other, ',
'e812' : 'but the journey never ends with an accomplished agenda and the circle goes round and round. This makes him/her confused ',
'e813' : 'and unfocused, sometimes giving oneself pressure and feeling of a sense of insecurity. EIGHT do not shun responsibility ',
'e814' : 'easily. EIGHT may appear to be reserved, conservative and passive in nature but socially he/she is much respected by the ',
'e815' : 'trustworthiness. EIGHT is dependable for these qualities.  He/she may appear to be firm but the inner character is kind and ',
'e816' : 'compassionate.  EIGHT can be rigid and cautious. His/her conservativeness makes it difficult when having to decide and make ',
'e817' : 'a timely decision. Loss of opportunities may be the consequence of the indecisiveness.',
'e818' : '',
'e911' : 'NINE denotes success and optimism. They are intelligent, open-minded and vigilant. This sets them to be strategically ',
'e912' : 'inclined to aim higher, constantly seeking for opportunities and improvement. Once NINE embraces an idea and an ',
'e913' : 'opportunity, they will be quick in planning, developing and executing, but not necessary particular with details. NINE can be ',
'e914' : 'eccentric and are well-groomed.  Their charisma and appreciative in the luxury of life makes them popular and a winner ',
'e915' : 'amongst associates and friends.  In reality, NINE are happiest with nature - quiet scenic environment. NINE are more inclined ',
'e916' : 'to look first into their own welfare before anything else. If not careful, NINE can lead to greed.',
'e917' : '',
'e918' : '',
'e1111' : 'Beware of relationship problems',
'e1112' : 'Beware of partnership split',
'e1113' : 'Beware of accidents, likely to suffer from surgical operations',
'e1114' : 'Attract back stabbing',
'e3366' : 'High risk taker, might involved in gambling activities and investment will not yield positive return',
'e1001' : 'Solution',
'e1002' : 'Wisdom',
'e1003' : 'Supporter',
'e1004' : 'Success',
'e1005' : 'Character',
'e1006' : 'Personal Attributes',
'e100' : 'Check for positioning of water features within the house or surrounding the house for fire-water clash.',
'e101' : 'Leadership',
'e102' : 'Communicative',
'e103' : 'Actions',
'e104' : 'Knowledge seeker',
'e105' : 'Sense of Direction',
'e106' : 'Wisdom',
'e107' : 'Supporter',
'e108' : 'Responsible',
'e109' : 'Success',
'e201' : 'Self-Centered',
'e202' : 'Indecisive',
'e203' : 'Impatient',
'e204' : 'Blunt',
'e205' : 'Stubborn',
'e206' : 'Timid',
'e207' : 'Hesitant',
'e208' : 'Stressful',
'e209' : 'Greed',
'e100000' : 'Health Watch',
'e100001' : 'Genetically Inherited Ailments',
'e100002' : 'Possible Ailments',
'e100016' : 'Respiratory system: Lung, Asthma, Skin allergies',
'e100027' : 'Kidney: Bladder: Impotence: Frequent Urination',
'e100038' : 'Heart: Cardiovascular diseases: Pain in the chest region: Blood circulations: Insomnia',
'e100049' : 'Bone structures: Liver area: Eyes: Tendon problems, Tension cramps [esp. near shoulder]: Skin diseases',
'e100050' : 'Digestive system - Stomach illness or upset: Indigestion: Constipation, Anaemia, Hemorrhoids: Joint pains: Arthritis',
'e200001' : 'Current Year',
'c100000' : '慎防健康状态',
'c100001' : '基因遺傳病',
'c100002' : '潛在性疾病',
'c100016' : '呼吸系統：肺部，哮喘病，皮膚敏感',
'c100027' : '腎臟：膀胱：陽痿：頻繁排尿',
'c100038' : '心臟：心血管疾病：胸部疼痛：血液循環：失眠',
'c100049' : '骨骼構造：肝臟：眼睛：肌腱問題，緊張抽筋[特別是近肩部]：皮 膚疾病 ',
'c100050' : '消化系統—腸胃病或腹痛：消化不良：便秘，貧血，痔瘡：關節 痛：關節炎 ',
'c200001' : '本年度',
'c1111' : '慎防感情/關係問題 ',
'c1112' : '會有合夥分裂的徵兆',
'c1113' : '提防意外，有可能會經歷外科手術',
'c1114' : '容易引來他人卑鄙手段的陷害',
'c3366' : '高度冒險家，也許會參與某些冒險活動, 投資將不會有正面的回饋',
'c1001' : '解决方案',
'c1002' : '智慧与财富',
'c1003' : '人缘',
'c1004' : '机会与成功',
'c1005' : '典型 ',
'c1006' : '個人屬性',
'c1007' : '内心世界 ',
'c1008' : '外心世界',
'c1009' : '潜意识',
'c100' : '檢查住宅内或屋子『週邊』的水流位置，以慎防水火相沖 的環境屬性 .',
'c101' : '领导',
'c102' : '沟通',
'c103' : '行动',
'c104' : '策划',
'c105' : '方向',
'c106' : '财富',
'c107' : '人缘',
'c108' : '责任',
'c109' : '成功者',
'c201' : '自我为中心',
'c202' : '犹豫不决',
'c203' : '缺乏耐力，坏脾气',
'c204' : '太过直言,单刀直入',
'c205' : '固执,具有破坏性',
'c206' : '较懦弱，胆怯',
'c207' : '做事慢条斯理',
'c208' : '忙碌，忧虑，压迫',
'c209' : '有商业头脑,但是永远会觉得不知足,变得很贪心',
'c11' : '独立，然而会引起别人在背后的恶意中伤，做事半途而废。',
'c12' : '滔滔不绝的你会引起别人在你背后恶意中伤。祸从口出。',
'c13' : '脾氣火爆,不但脾气不好，做事又没耐心，一个非常忙碌的人。',
'c14' : '不但是个优秀的策划者，而且做事还很有规矩，但是缺乏信心，最終還是無法畫 龍點睛 .',
'c15' : '非常坚持相信自己的原则来办事。',
'c16' : '自个儿卖力以达到成功和财富的梦想，新潮和外表很时髦。',
'c17' : '吸引不少支持者，不过压力很大，时常有到处漫游的机会。',
'c18' : '时常出外[在道路上]而且压力也很大。',
'c19' : '涉及的生意或事务都需要自己卖力和奋斗。',
'c21' : '很有权的说话和做事。',
'c22' : '容易心软，滔滔不绝，是个收多过施的小人。',
'c23' : '很情绪化，很容易激发自己。',
'c24' : '一个在生意话题上滔滔不绝的人才，沟通能力极好。',
'c25' : '一个拥有很强原则的人，能够吸引别人的注意力。',
'c26' : '是一个喜欢提及有关钱财与金融的人。',
'c27' : '擁有超凡魅力的吸引個體，容易吸引支持者。',
'c28' : '一个经常很忙碌和滔滔不绝的人。通常适宜在畅销部门立足。',
'c29' : '一个很喜欢谈论有关生意话题的人。',
'c31' : '在还没有成功之前须要别人不断地勉励。',
'c32' : '说话很直接和坦白，想到什么就讲出口从来没有考虑到其后果。',
'c33' : '极度情绪化，冲动以及没有耐性。',
'c34' : '敏捷的策划者或编组，即时做出行动。',
'c35' : '不但情绪化，善变，而且还很容易被激怒。',
'c36' : '大花筒。',
'c37' : '有可能会背叛支持者。',
'c38' : '极度情绪化，时常都非常忙碌。',
'c39' : '很忙碌的寻求生意良机。很可惜徒劳无功。',
'c41' : '任務/事情時常因特況而無法成功地完成，終是停滯不進。',
'c42' : '是非常出色的策划者和演说家。',
'c43' : '一个精打细算的策划者。同时还能吸引很多的支持者。',
'c44' : '有很多计划和意见，可是过份的策划。凡事只考虑到利益的因素而已。',
'c45' : '将会策划，想尽一切方法及手段去达到目的。',
'c46' : '金融策划者。',
'c47' : '是一个很精明的策划者，同时也帮忙别人策划。',
'c48' : '是一个很忙碌的策划者，经常压力很大。一直在漩涡中徘徊。',
'c49' : '是一个时常策划如何达到成功之路的战略家。',
'c51' : '是一个做事非常有原则的人但是非常自我。时常出国。',
'c52' : '是一个生性固执而且依足原则来说话的人。',
'c53' : '是个情绪化和做事没有毅力的人。',
'c54' : '用尽一切方法及手段让别人为他去达到目的。',
'c55' : '是个非常固执，自私自利，坏脾气而且情绪化的人，导致自我毁灭。',
'c56' : '很小心的处理钱财问题，是个名副其实的守财奴。',
'c57' : '有机会接触高层公务人者或社会名流。',
'c58' : '是一个非常有创意的人。不过所有事情都必须自己承担。',
'c59' : '有着非常古板的思想，自以为是。',
'c61' : '喜歡花錢於自己的身上,挥金如土。',
'c62' : '信口开河，时常打回原型。',
'c63' : '是个大花筒。时常做出很急促的投资。',
'c64' : '投入於教育學，自我增值. 时常花费在学业上寻求知识。',
'c65' : '守财奴。',
'c66' : '钱财方面进出很快，很难储蓄。',
'c67' : '会以金钱来买通或影响支持者的拥护。',
'c68' : '一个衷于研究者，很难储蓄。',
'c69' : '熱衷於投資；是個敢于冒險的人物.',
'c71' : '会吸引朋友在背后议论。',
'c72' : '吸引支持者，友善的性格。',
'c73' : '支持者来来去去。',
'c74' : '有机会会遇到高人或名师给于你肺腑之言。',
'c75' : '朋友或支持者可能会背叛你，出卖你[或倒转]。',
'c76' : '支持者会以资本资助你，给你提供投资提示及劝告。',
'c77' : '你拥有很多支持者，不过你有可能会利用他们。',
'c78' : '支持者会向你施压。',
'c79' : '支持者会协助你达到成就，支持者有可能会演变成生意伙伴。',
'c81' : '是一个很勤劳和事事关心的领袖，很忙碌和压力重重。',
'c82' : '忠言逆耳。所以很多时候需要自己解决问题。',
'c83' : '情绪化没耐性，容易被激怒。',
'c84' : '很多有用的意见不过一直徘徊找不到出路。',
'c85' : '一个很有创意的人不过为自己带来很多麻烦。',
'c86' : '有很多创意性的赚钱方法，同时需要遍游四海以寻找生计。',
'c87' : '辛劳的你会遇到知音的欣赏。向支持者施压。',
'c88' : '是一个很忙碌，情绪化和非常大压力的人。',
'c89' : '一直徘徊在漩涡中找不到突破。',
'c91' : '孤独或单身汉。',
'c92' : '你附有很强地说服力，喜爱谈说有关生意上的论题。',
'c93' : '注意范围很小，在漩涡中徘徊。',
'c94' : '在事业上有机会发展，不过没有肯定的目标。',
'c95' : '很多问题围绕在身边，时常都自私自利不顾别人。',
'c96' : '生意或投资方面会有很好的利润或回酬。',
'c97' : '生意或投资会有丰厚的报酬。',
'c98' : '经过一番努力后还是得不到成果，一再从新开始。',
'c99' : '失去很多良好的生意机会，做事不够注意力，很贪心。',
'c111' : '智慧的根源。這類型的人充滿著虛心向學的態度而且也具有甚強的分析能力。',
'c112' : '之所以這樣,他/她們往往是群体中最有經驗的領導人。只可惜的是,一旦這類人有歪念,',
'c113' : '他們就會變得“貪得無厭。1亦代表著這類人做事非常仔細和謹慎。',
'c114' : '他們也俱備著強勁的創意及謹慎的思想。一旦這創新及謹慎的思想被啟發,就會帶來',
'c115' : '無限的財富。除此之外, 這類型的人也是一個能夠娛樂大眾以及持有良好人際關系的',
'c116' : '焦點人物。通常財富會在34歲至42歲來臨。他們是天生的領導者以及具有強大的特權。',
'c117' : '同時,他們也稱得上是個講道義的義士。另外,他們也吸引異性的支援與協助。',
'c118' : '',
'c211' : '熟練多方面的技巧及有著开朗的性情。處世冷静及友善。非常注意衛生和整洁。',
'c212' : '一個非常勤勞及思想成熟的人。通常他們多參與年长之輩。',
'c213' : '而且是個聽話的聆聽者但這并不代表他們會一百巴仙随從忠告。',
'c214' : '如果给予他們任何事務,這類型的人能夠帶領整支隊伍。他們精通人事方面的一切事務。',
'c215' : '此外,他們會凭空想象不切實際和固執于自己的原則。而其最為負面的一點就是他們會',
'c216' : '制造是非問題。然而，2的為人雖勤快，但他們卻敏感於周遭的事物。',
'c217' : '最棒的諮詢者與建議者, 因他們會認真地聆聽他人 的意見，並適時地給予他們一些',
'c218' : '善意的忠言。他們可謂是 個很堅定的獨立個體.',
'c311' : '活躍和具有自動自觉的態度。這類型的人很清楚自己的人生目標。他們善于分辨是非黑白。',
'c312' : '擁有多方面的能力與天份。亦可成為非常富裕及有潛能的人。',
'c313' : '通常,他們會在30歲前就在社會上有著固定的地位與成就。',
'c314' : '然而,這類型的人做事總是操之過急,没有耐性和脾氣也相當的壞。',
'c315' : '他們做事總是因為不夠堅持而耽誤其後果。很多時候,他們會因一時的沖動而胡言乱語。',
'c316' : '與此同時,他們的感情生活也不太如意。如果不加以控制這些感情事,往往會引起',
'c317' : '火陷的局面。',
'c318' : '',
'c411' : '擁有知識淵博。富有文藝細胞以及能在考試中榜上題名。',
'c412' : '是個講究信誉以及能很快地适應在新環境和社群中。',
'c413' : '仁慈及开朗。外向,喜歡環绕世界和徜徉無束的生活方式。年少時就會是一個非常',
'c414' : '出色的人士。',
'c415' : '如果這是一個女士,她會是個很被寵愛,很會交際應酬及很友善的人。',
'c416' : '每每遇到挫折,他們會很快的爬起來,重新振作。4類型的人在理財方面會比較差。',
'c417' : '必須小心處理感情事或婚姻的結合。要不然後果就不堪設想了。',
'c418' : '',
'c511' : '擁有很倔強的性格。出生于很強的領導力。开朗的性情促使他們能夠領導部屬。',
'c512' : '通常他們位于萬人之上的位置。以非常尖銳的直觉來處理事務。',
'c513' : '一個非常勤勞而且會在人生中較後的日子里有所成就。',
'c514' : '一個現實主義者,凡事一絲不苟而且也不會憑空幻想不求實際。',
'c515' : '如果屬于5的人生长在底層或貧困的環境中,他們會變得固執和犹如铁石般的心肠。',
'c516' : '相反的, 如果他們能夠放松心情,不拘小節和减低他們固執與執著的態度,他們必定會',
'c517' : '受萬人的愛戴與尊敬。',
'c518' : '',
'c611' : '很強的生存意識。6能控制財富和興隆。生活規律化而且有著高尚的品味。',
'c612' : '6字代表著在事業里有所展望,譬如在教育界,藝术行業和宗教社團里。',
'c613' : '這類型的人將會成為社會上举足輕重的典型領袖。',
'c614' : '然而,這种人多半會是個傲慢不羁而且不輕易為五斗米而折腰的大丈夫。',
'c615' : '很多時候他/她們不願意聽取上司的意見。可是他/她們會很照顧部屬們的利益與要求。',
'c616' : '運氣會在45歲以後來臨。',
'c617' : '他們是個保守 派的決策者，往往是需經過計算，方會冒險行動的人物。',
'c618' : '6皆可謂是個優秀的執行者，因為他們負責任及經常會照顧 自己部屬的利益與要求',
'c711' : '有熟悉的技巧和能夠很謹慎的處理事務。他們絕不會是個忘恩負義的負心人。',
'c712' : '相反的,他們珍惜及感激曾幫助他們渡過难關的恩人。他們是個很熱情及附有愛心的人。',
'c713' : '不過,﹐屬7字的人喜好爭辩事情的好壞,同時他們有本領去歪曲事實的真相。',
'c714' : '之所以這樣,他們會引起谣言及议論紛紛。他們嚮往名成利就。',
'c715' : '通常,他們的思想變化無常,很容易受影響,臨時改變初衷和举棋不定。',
'c716' : '婚姻有出現問題的可能性。',
'c717' : '這類人士會積極參于及精通于夜生活般娛樂性行業。',
'c718' : '',
'c811' : '文静,守舊及被動的性情。不過在大夥兒中他們會變得比較活潑生動。很有安全感和講',
'c812' : '‘義氣’。一個值得信賴的人。',
'c813' : '做事不會衰竭,不過很多時候會显示有點一头雾水的感觉。',
'c814' : '他們都希望成為社會上的名人。外表看起來堅強不屈,其實內心却溫柔似水。',
'c815' : '很多時候﹐因為他們太過謹慎和堅信自己的概念而導致失去幾會的元素。',
'c816' : '8擁有值得他人信賴的個 人屬性。不過，他/她的外觀看似堅定，但其實他/她的',
'c817' : '內心世界是柔情和憐憫的[屬外剛内柔型].',
'c818' : '',
'c911' : '性格客觀及思想开朗。喜歡给予人人一個最整齊美觀的照型。',
'c912' : '很有文化,聰明過人谨惕性极高的人。屬9的人知道在時机成熟時做出任何反應。',
'c913' : '很會討人歡心。做事快而準, 办事能力也很高。不過不夠細心。',
'c914' : '他們不會顧及别人的感受[尤其是對下屬們]。內柔外剛。很情绪化。',
'c915' : '年老時不會有太多的朋友﹐因此而感到非常孤獨。幸運星將會在中年35歲以上降臨。',
'c916' : '不過，在現實生活中，9則 是個嚮往幸福快樂與自然寧靜的優美環境。',
'c917' : '9非常注重個人 的福利多過於其他事件。相對而言，9亦容易萌起貪婪的信念.',
'c918' : '',
'c951' : '外表让人觉得自己很大方，有很多朋友，但内心是空虚，寂寞。很想做领导者，但不能。',
'c952' : '很喜欢讲，但是未必会讲。不跟别人谈心声。',
'c953' : '很想行动，但是不能，只是想罢了，没有行动。',
'c954' : '计划给自己，没有展现出来。不准时。',
'c955' : '内心挣扎，找不到出路。不爱受影响。',
'c956' : '内心很想钱，想学智慧，贤妻良母。',
'c957' : '不甘寂寞，会埋怨。',
'c958' : '不可踩到他的尾巴，自己制造压力。',
'c959' : '要很多次成功，成功之后，还是不够，不知足。',
'c961' : '原则很强，独立型，很孤单。',
'c962' : '很想跟人沟通，但不能沟通。心不在焉，要逼他才讲。',
'c963' : '某某事情会让他发脾气，做事紧张。',
'c964' : '给人家感觉到没有策划，但是他是有一部分策划。策划自己喜欢的事。',
'c965' : '犹豫不决，找寻出路。',
'c966' : '你不可以让另一半对你不忠，赚钱是为了家庭，对钱比较重要。',
'c967' : '喜欢交朋友，恨嫁（女）。',
'c968' : '你本身看起来没有压力，但是，无形中会发脾气，会有压力，很忙碌。',
'c969' : '很想成功，很想让别人认同。',
'c9713' : '理想主义者。这类型的人有许多稀奇古怪的主意。他们缺乏实际的行动及执行能力。'  ,
'c9723' : '他们做事虽然非常严谨小心，但有时卻会过于愤世妒俗，而停滞不前。很喜欢完美.',
'c9716' : '现实主义者。他们为人比较脚踏实地，不会做无谓的空想。一旦構思妥当，',
'c9726' : '他们就会全力以赴，用心去实践。凡事都讲究现实.',
'c9719' : '梦想远见者。他们敢于追寻梦想，懂得享受生活。他们在实际与物质之间可以取得',
'c9729' : '很好的平衡，往往是个生活大赢家。'
};

function displayData()
{
var str=document.getElementById("birthday_day").value+document.getElementById("birthday_month").value+document.getElementById("birthday_year").value;
var vday=str.substr(0,2);
var vmonth=str.substr(2,2);
var vyear=str.substr(4,4);
var a=vday.substr(0,1);
var b=vday.substr(1,1);
var c=vmonth.substr(0,1);
var d=vmonth.substr(1,1);
var e=vyear.substr(0,1);
var f=vyear.substr(1,1);
var g=vyear.substr(2,1);
var h=vyear.substr(3,1);
var i=VCalc(a,b);
var j=VCalc(c,d);
var k=VCalc(e,f);
var l=VCalc(g,h);
var m=VCalc(i,j);
var n=VCalc(k,l);
var o=VCalc(m,n);

var p=VCalc(n,o);
var q=VCalc(m,o);
var r=VCalc(p,q);

var u=VCalc(i,m);
var v=VCalc(j,m);
var s=VCalc(u,v);

var w=VCalc(k,n);
var x=VCalc(l,n);
var t=VCalc(w,x);
  
var totalWF= WFCrash(i,j)+ WFCrash(j,k)+ WFCrash(k,l) + WFCrash(i,m)+ WFCrash(j,m);
    totalWF= totalWF + WFCrash(k,n)+ WFCrash(l,n)+ WFCrash(m,n)+  WFCrash(m,o)+  WFCrash(n,o);
    
var langUse='e';
	if (document.getElementById("lang").value == '1') 
	{ 
		langUse='c';
		}
	
var cij=VChatData[langUse+i+j];
var ckl=VChatData[langUse+k+l];
var cmn=VChatData[langUse+m+n];

var cuv=VChatData[langUse+u+v];
var cwx=VChatData[langUse+w+x];
var cpq=VChatData[langUse+p+q];
var waterFire='[' + VChatData[langUse+'100'] + ']';
var cAll=cij+"\t\n"+ckl+"\t\n"+cmn +"\t\n"+cuv +"\t\n"+cwx +"\t\n"+cpq  ;
if(totalWF >0){
var cAll=cij+"\t\n"+ckl+"\t\n"+cmn +"\t\n"+cuv +"\t\n"+cwx +"\t\n"+cpq +"\t\n" + waterFire  ;
        //$GetCharacter=$vc[$LangUse.'100'];
        //imagettftext($imgcord, 12, 0, $xpos, $ypos+770, $red, $font,$GetCharacter.' x '.$totalWF);
    }
/*document.getElementById("demo").innerHTML=vday + ' = ' + vmonth + ' = ' + vyear;
*/
//var Character=trim(document.getElementById("name").value);
//document.getElementById("demo").innerHTML=ab;
document.getElementById("demo").innerHTML=cAll;
}
function trim(a) {
	return a.replace(/^s*(S*(s+S+)*)s*$/, "$1");
}
function VCalc( d1,d2)
{
    var total=Number(d1)+Number(d2);
	var strTotal=String(total);
   if (strTotal.length > 1) 
	{
		return (String(Number(strTotal.substr(0,1))+ Number(strTotal.substr(1,1))));
    }
	else	return strTotal;
}

function WFCrash(d1,d2)
{
    if (((d1=='2' || d1=='7') && (d2=='3' || d2=='8'))
    || ((d1=='3' || d1=='8') && (d2=='2' || d2=='7')))
    {return 1;}
    return 0;
}

